# Generated by Django 5.1.3 on 2025-01-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExtractedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name1', models.CharField(blank=True, max_length=255, null=True)),
                ('stext_content1', models.TextField(blank=True, null=True)),
                ('student_name2', models.CharField(blank=True, max_length=255, null=True)),
                ('stext_content2', models.TextField(blank=True, null=True)),
                ('student_name3', models.CharField(blank=True, max_length=255, null=True)),
                ('stext_content3', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
