# Generated by Django 5.1.3 on 2025-01-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_remove_studentanswer_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentanswer',
            old_name='extracted_text_a',
            new_name='section_a_text',
        ),
        migrations.RenameField(
            model_name='studentanswer',
            old_name='extracted_text_b',
            new_name='section_b_text',
        ),
        migrations.RenameField(
            model_name='studentanswer',
            old_name='extracted_text_c',
            new_name='section_c_text',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='max_marks_a',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='max_marks_b',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='max_marks_c',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='course_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='roll_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='student_name',
            field=models.CharField(max_length=200),
        ),
    ]
