# Generated by Django 5.1.3 on 2025-01-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_rename_extracted_text_a_studentanswer_section_a_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='max_marks_a',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='max_marks_b',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='max_marks_c',
        ),
    ]
